server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fishmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: test
    password: abcd1234

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
